relativeURLs = true
baseURL = "/"
title = "Racadegatos"
author = "Hugo Norte"
copyright = "Copyright Â© 2023, Hugo Norte and the Hugo Authors; all rights reserved."
paginate = 3
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
